// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHyUuLUm_Mwte-vuD5P69jT26AzxwbRvE',
    appId: '1:494938427471:web:d3e27c3c06dea475279a3a',
    messagingSenderId: '494938427471',
    projectId: 'flashchat-79294',
    authDomain: 'flashchat-79294.firebaseapp.com',
    storageBucket: 'flashchat-79294.appspot.com',
    measurementId: 'G-3FMM1F58FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAbNDTXejNC_49xnkk8y7vDoqbX98MiGg',
    appId: '1:494938427471:android:b4104d3246b5b410279a3a',
    messagingSenderId: '494938427471',
    projectId: 'flashchat-79294',
    storageBucket: 'flashchat-79294.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0dxm6ck78crqNgTxt0P5J-q7w_SV-bq0',
    appId: '1:494938427471:ios:7ce18691a358188e279a3a',
    messagingSenderId: '494938427471',
    projectId: 'flashchat-79294',
    storageBucket: 'flashchat-79294.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );
}
